// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Base() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\" data-theme=\"light\"><head><title>Juan P Echeverry - Software Developer</title><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.cyan.min.css\"><script src=\"https://kit.fontawesome.com/18a9386424.js\" crossorigin=\"anonymous\"></script><link rel=\"icon\" type=\"image/x-icon\" href=\"/static/images/favicon.ico\"></head><body class=\"container\" style=\"max-width: 800px; padding: 0 20px;\"><nav><ul style=\"font-weight: bold;\"><li><a href=\"/\">Juan P</a></li></ul><ul style=\"font-weight: bold;\"><li><a href=\"https://github.com/jpecheverryp/jpechdev\" target=\"_blank\"><i class=\"fa-brands fa-github\"></i> Source</a></li><li><a href=\"/about\">About</a></li><li><a href=\"/contact\">Contact</a></li></ul></nav><main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</main><footer style=\"text-align: center;\"><p>&copy; 2025 Juan P Echeverry. All Rights Reserved.</p><nav style=\"display: block; margin: 0 auto;\"><ul style=\"display: block; margin: 0 auto; height: fit-content;\"><li style=\"padding: 0 0.5rem;\"><a href=\"/github\" target=\"_blank\"><i class=\"fa-brands fa-github\"></i></a></li><li style=\"padding: 0 0.5rem;\"><a href=\"/linkedin\" target=\"_blank\"><i class=\"fa-brands fa-linkedin\"></i></a></li></ul></nav></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
